### PR TITLE
Test system time independent of test id

### PR DESCRIPTION
**Pull request by bogdanSkipr**

### CODE REVIEW

**Comment by JensSkipr** [comment]
@bogdanSkipr @mikSkipr what's the reason for this change?

**Comment by mikSkipr** [comment]
> 
Because of recurring + split + suspension, there was a point risen that we need a way to trigger cron job for updating summary & topup on staging for test purposes.

**Comment by JensSkipr** [comment]
Ok, but I don't see how providing this time in the request would trigger the cron job. Instead I would suggest we expose our cron jobs somehow to the E2E testing script (authenticated!!). Might be related to a 10% project I submitted to Stéphane this week:
image

**Comment by JensSkipr** [comment]
Maybe to clarify my concern:
If people discover somehow you can set the time in each request, this might be a major security issue. E.g. use of expired tokens by emulating an earlier day. Due to this, we originally restricted this feature to calls targetting the E2E DB and prevent its use from the real DB. So, from a security PoV, I think it's a really important consideration.

**Comment by bogdanSkipr** [comment]
I understand the security concerns. Then I'll just add this test time as parameter to the internal trigger endpoint that we already implemented, this way there's no security risks.

**Pull request closed without merging**
